# Generated by Django 4.0.3 on 2024-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
